// src/lib/mock-data.ts
import { Service } from '@/types/service';

export const services: Service[] = [
  // Cleaning
  {
    id: '1',
    title: 'Home Cleaning Service',
    description: 'Professional home cleaning for apartments and houses.',
    price: 2500,
    rating: 4.5,
    category: {
      id: 'c1',
      name: 'Cleaning',
      slug: 'cleaning',
    },
    image: '/images/cleaning.jpg',
    location: 'Karachi',
    createdAt: new Date().toISOString(),
    phone: '+92 300 1111111',
    email: 'cleaning@example.com',
  },
  {
    id: '2',
    title: 'Office Cleaning Service',
    description: 'Commercial cleaning services for offices and buildings.',
    price: 4000,
    rating: 4.6,
    category: {
      id: 'c1',
      name: 'Cleaning',
      slug: 'cleaning',
    },
    image: '/images/office-cleaning.jpg',
    location: 'Lahore',
    createdAt: new Date().toISOString(),
    phone: '+92 300 2222222',
    email: 'officecleaning@example.com',
  },

  // Maintenance
  {
    id: '3',
    title: 'AC Repair & Installation',
    description: 'Expert AC repair and installation services.',
    price: 4000,
    rating: 4.7,
    category: {
      id: 'c2',
      name: 'Maintenance',
      slug: 'maintenance',
    },
    image: '/images/ac.jpg',
    location: 'Lahore',
    createdAt: new Date().toISOString(),
    phone: '+92 300 3333333',
    email: 'acservice@example.com',
  },
  {
    id: '4',
    title: 'Plumbing Repair Service',
    description: 'Professional plumbing repair for leaks, pipes, and fittings.',
    price: 1800,
    rating: 4.3,
    category: {
      id: 'c2',
      name: 'Maintenance',
      slug: 'maintenance',
    },
    image: '/images/plumbing.jpg',
    location: 'Islamabad',
    createdAt: new Date().toISOString(),
    phone: '+92 300 4444444',
    email: 'plumbing@example.com',
  },
  {
    id: '5',
    title: 'Electrician Services',
    description: 'Certified electricians for wiring and installations.',
    price: 2200,
    rating: 4.6,
    category: {
      id: 'c2',
      name: 'Maintenance',
      slug: 'maintenance',
    },
    image: '/images/electrician.jpg',
    location: 'Rawalpindi',
    createdAt: new Date().toISOString(),
    phone: '+92 300 5555555',
    email: 'electrician@example.com',
  },

  // Design
  {
    id: '6',
    title: 'Graphic Design Service',
    description: 'Creative logo and branding design solutions.',
    price: 5000,
    rating: 4.8,
    category: {
      id: 'c3',
      name: 'Design',
      slug: 'design',
    },
    image: '/images/design.jpg',
    location: 'Karachi',
    createdAt: new Date().toISOString(),
    phone: '+92 300 6666666',
    email: 'design@example.com',
  },
  {
    id: '7',
    title: 'Interior Design Consultation',
    description: 'Professional interior design services for homes and offices.',
    price: 8000,
    rating: 4.9,
    category: {
      id: 'c3',
      name: 'Design',
      slug: 'design',
    },
    image: '/images/interior-design.jpg',
    location: 'Lahore',
    createdAt: new Date().toISOString(),
    phone: '+92 300 7777777',
    email: 'interiordesign@example.com',
  },

  // IT Services
  {
    id: '8',
    title: 'Web Development Service',
    description: 'Modern responsive website development.',
    price: 15000,
    rating: 4.9,
    category: {
      id: 'c4',
      name: 'IT Services',
      slug: 'it-services',
    },
    image: '/images/webdev.jpg',
    location: 'Lahore',
    createdAt: new Date().toISOString(),
    phone: '+92 300 8888888',
    email: 'webdev@example.com',
  },
  {
    id: '9',
    title: 'Laptop Repair Service',
    description: 'Fast laptop repair and hardware troubleshooting.',
    price: 3500,
    rating: 4.5,
    category: {
      id: 'c4',
      name: 'IT Services',
      slug: 'it-services',
    },
    image: '/images/laptop.jpg',
    location: 'Hyderabad',
    createdAt: new Date().toISOString(),
    phone: '+92 300 9999999',
    email: 'laptoprepair@example.com',
  },

  // Beauty
  {
    id: '10',
    title: 'Makeup Artist Booking',
    description: 'Professional bridal and event makeup services.',
    price: 8000,
    rating: 4.7,
    category: {
      id: 'c5',
      name: 'Beauty',
      slug: 'beauty',
    },
    image: '/images/makeup.jpg',
    location: 'Faisalabad',
    createdAt: new Date().toISOString(),
    phone: '+92 300 1010101',
    email: 'makeup@example.com',
  },

  // Events
  {
    id: '11',
    title: 'Photography for Events',
    description: 'Professional photography for weddings and events.',
    price: 12000,
    rating: 4.8,
    category: {
      id: 'c7',
      name: 'Events',
      slug: 'events',
    },
    image: '/images/photography.jpg',
    location: 'Peshawar',
    createdAt: new Date().toISOString(),
    phone: '+92 300 1112121',
    email: 'photography@example.com',
  },

  // Automotive
  {
    id: '12',
    title: 'Car Wash & Detailing',
    description: 'Premium car wash and interior detailing service.',
    price: 2000,
    rating: 4.4,
    category: {
      id: 'c6',
      name: 'Automotive',
      slug: 'automotive',
    },
    image: '/images/carwash.jpg',
    location: 'Multan',
    createdAt: new Date().toISOString(),
    phone: '+92 300 1212121',
    email: 'carwash@example.com',
  },
];