// src/lib/mock-data.ts
import { Service } from '@/types/service';

export const services: Service[] = [
  // Cleaning
  {
    id: '1',
    title: 'Home Cleaning Service',
    description: 'Professional home cleaning for apartments and houses.',
    price: 2500,
    rating: 4.5,
    category: {
      id: 'c1',
      name: 'Cleaning',
      slug: 'cleaning',
    },
    image: '/images/cleaning.jpg',
    location: 'Eastleigh',
    address: '123 Main Street, Karachi',
    openingHours: 'Mon-Sat: 9am - 6pm',
    createdAt: new Date().toISOString(),
    phone: '+92 300 1111111',
    email: 'cleaning@example.com',
    website: 'https://cleaningService.com',
    bookingUrl: 'https://cleaningService.com/book',
    coordinates: {
      latitude: 24.8607,
      longitude: 67.0011,
    },
  },
  {
    id: '2',
    title: 'Office Cleaning Service',
    description: 'Commercial cleaning services for offices and buildings.',
    price: 4000,
    rating: 4.6,
    category: {
      id: 'c1',
      name: 'Cleaning',
      slug: 'cleaning',
    },
    image: '/images/office-cleaning.jpg',
    location: 'Winchester',
    address: '456 Business, Lahore',
    openingHours: 'Mon-Sat: 9am -5pm',
    createdAt: new Date().toISOString(),
    phone: '+92 300 2222222',
    email: 'officecleaning@example.com',
    website: 'https://officelearning.com',
    bookingUrl: 'https://officelearning.com/book',
    coordinates: {
      latitude: 31.5497,
      longitude: 74.3436,
    },
  },

  // Maintenance
  {
    id: '3',
    title: 'AC Repair & Installation',
    description: 'Expert AC repair and installation services.',
    price: 4000,
    rating: 4.7,
    category: {
      id: 'c2',
      name: 'Maintenance',
      slug: 'maintenance',
    },
    image: '/images/ac.jpg',
    location: 'Southampton',
    address: '789  Street, Lahore',
    openingHours: 'Mon-Sat: 9am - 7pm',
    createdAt: new Date().toISOString(),
    phone: '+92 300 3333333',
    email: 'acservice@example.com',
    website: 'https://ACRepairService.com',
    bookingUrl: 'https://ACRepairService.com/book',
    coordinates: {
      latitude: 38.07,
      longitude: 65.011,
    },
  },
  {
    id: '4',
    title: 'Plumbing Repair Service',
    description: 'Professional plumbing repair for leaks, pipes, and fittings.',
    price: 1800,
    rating: 4.3,
    category: {
      id: 'c2',
      name: 'Maintenance',
      slug: 'maintenance',
    },
    image: '/images/plumbing.jpg',
    location: 'Portsmouth',
    address: '111  Street, Islamabad',
    openingHours: 'Mon-Sat: 9am - 6pm',
    createdAt: new Date().toISOString(),
    phone: '+92 300 4444444',
    email: 'plumbing@example.com',
    bookingUrl: 'https://plumbingService.com/book',
    coordinates: {
      latitude: 33.6844,
      longitude: 73.0479,
    },
  },
  {
    id: '5',
    title: 'Electrician Services',
    description: 'Certified electricians for wiring and installations.',
    price: 2200,
    rating: 4.6,
    category: {
      id: 'c2',
      name: 'Maintenance',
      slug: 'maintenance',
    },
    image: '/images/electrician.jpg',
    location: 'Eastleigh',
    address: '222  Street, Rawalpindi',
    openingHours: 'Mon-Sat: 9am - 6pm',
    createdAt: new Date().toISOString(),
    phone: '+92 300 5555555',
    email: 'electrician@example.com',
    website: 'https://electricianService.com',
    bookingUrl: 'https://electricianService.com/book',
    coordinates: {
      latitude: 22.877,
      longitude: 360011,
    },
  },

  // Design
  {
    id: '6',
    title: 'Graphic Design Service',
    description: 'Creative logo and branding design solutions.',
    price: 5000,
    rating: 4.8,
    category: {
      id: 'c3',
      name: 'Design',
      slug: 'design',
    },
    image: '/images/design.jpg',
    location: 'Southampton',
    address: '333  Street, Karachi',
    openingHours: 'Mon-Sat: 9am - 6pm',
    createdAt: new Date().toISOString(),
    phone: '+92 300 6666666',
    email: 'design@example.com',
  },
  {
    id: '7',
    title: 'Interior Design Consultation',
    description: 'Professional interior design services for homes and offices.',
    price: 8000,
    rating: 4.9,
    category: {
      id: 'c3',
      name: 'Design',
      slug: 'design',
    },
    image: '/images/interior-design.jpg',
    location: 'Winchester',
    address: '444  Street, Lahore',
    openingHours: 'Mon-Sat: 9am - 6pm',
    createdAt: new Date().toISOString(),
    phone: '+92 300 7777777',
    email: 'interiordesign@example.com',
    website: 'https://ProfessionalInteriorDesign.com',
    bookingUrl: 'https://ProfessionalInteriorDesign.com/book',
    coordinates: {
      latitude: 24.8607,
      longitude: 67.0011,
    },
  },

  // IT Services
  {
    id: '8',
    title: 'Web Development Service',
    description: 'Modern responsive website development.',
    price: 15000,
    rating: 4.9,
    category: {
      id: 'c4',
      name: 'IT Services',
      slug: 'it-services',
    },
    image: '/images/webdev.jpg',
    location: 'Portsmouth',
    address: '555  Street, Lahore',
    openingHours: 'Mon-Sat: 9am - 6pm',
    createdAt: new Date().toISOString(),
    phone: '+92 300 8888888',
    email: 'webdev@example.com',
    website: 'https://webdevService.com',
    bookingUrl: 'https://webdevService.com/book',
    coordinates: {
      latitude: 34.8607,
      longitude: 67.0011,
    },
  },
  {
    id: '9',
    title: 'Laptop Repair Service',
    description: 'Fast laptop repair and hardware troubleshooting.',
    price: 3500,
    rating: 4.5,
    category: {
      id: 'c4',
      name: 'IT Services',
      slug: 'it-services',
    },
    image: '/images/laptop.jpg',
    location: 'Eastleigh',
    address: '666  Street, Hyderabad',
    openingHours: 'Mon-Sat: 9am - 6pm',
    createdAt: new Date().toISOString(),
    phone: '+92 300 9999999',
    email: 'laptoprepair@example.com',
    website: 'https://laptoprepairService.com',
    bookingUrl: 'https://laptoprepairService.com/book',
    coordinates: {
      latitude: 21.8607,
      longitude: 71.2111,
    },
  },

  // Beauty
  {
    id: '10',
    title: 'Makeup Artist Booking',
    description: 'Professional bridal and event makeup services.',
    price: 8000,
    rating: 4.7,
    category: {
      id: 'c5',
      name: 'Beauty',
      slug: 'beauty',
    },
    image: '/images/makeup.jpg',
    location: 'Winchester',
    address: '777  Street, Faisalabad',
    openingHours: 'Mon-Sat: 9am - 6pm',
    createdAt: new Date().toISOString(),
    phone: '+92 300 1010101',
    email: 'makeup@example.com',
    website: 'https://makeupService.com',
    bookingUrl: 'https://makeupService.com/book',
    coordinates: {
      latitude: 55.1245,
      longitude: 27.0011,
    },
  },

  // Events
  {
    id: '11',
    title: 'Photography for Events',
    description: 'Professional photography for weddings and events.',
    price: 12000,
    rating: 4.8,
    category: {
      id: 'c7',
      name: 'Events',
      slug: 'events',
    },
    image: '/images/photography.jpg',
    location: 'Southampton',
    address: '888  Street, Peshawar',
    openingHours: 'Mon-Sat: 9am - 6pm',
    createdAt: new Date().toISOString(),
    phone: '+92 300 1112121',
    email: 'photography@example.com',
    website: 'https://ProfesionalPhotography.com',
    bookingUrl: 'https://ProfesionalPhotography.com/book',
    coordinates: {
      latitude: 67.881,
      longitude: 57.0011,
    },
  },

  // Automotive
  {
    id: '12',
    title: 'Car Wash & Detailing',
    description: 'Premium car wash and interior detailing service.',
    price: 2000,
    rating: 4.4,
    category: {
      id: 'c6',
      name: 'Automotive',
      slug: 'automotive',
    },
    image: '/images/carwash.jpg',
    location: 'Portsmouth',
    address: '999  Street, Multan',
    openingHours: 'Mon-Sat: 9am - 6pm',
    createdAt: new Date().toISOString(),
    phone: '+92 300 1212121',
    email: 'carwash@example.com',
    website: 'https://PremiumCarWash.com',
    bookingUrl: 'https://PremiumCarWash.com/book',
    coordinates: {
      latitude: 22.5541,
      longitude: 67.0011,
    },
  },

  // All Hampshire Services
  {
    id: '13',
    title: 'Hampshire Wide Delivery Service',
    description: 'Fast and reliable delivery service across all Hampshire.',
    price: 1500,
    rating: 4.6,
    category: {
      id: 'c8',
      name: 'Delivery',
      slug: 'delivery',
    },
    image: '/images/delivery.jpg',
    location: 'All Hampshire',
    address: 'Central Hub, Hampshire',
    openingHours: 'Mon-Sun: 8am - 8pm',
    createdAt: new Date().toISOString(),
    phone: '+92 300 1313131',
    email: 'delivery@example.com',
    website: 'https://hampshiredelivery.com',
    bookingUrl: 'https://hampshiredelivery.com/book',
    coordinates: {
      latitude: 51.0504,
      longitude: -1.4084,
    },
  },
  {
    id: '14',
    title: 'Regional Consultant Services',
    description: 'Business consulting services available throughout Hampshire.',
    price: 6000,
    rating: 4.7,
    category: {
      id: 'c9',
      name: 'Consulting',
      slug: 'consulting',
    },
    image: '/images/consulting.jpg',
    location: 'All Hampshire',
    address: 'Business Park, Hampshire',
    openingHours: 'Mon-Fri: 9am - 5pm',
    createdAt: new Date().toISOString(),
    phone: '+92 300 1414141',
    email: 'consulting@example.com',
    website: 'https://hampshireconsulting.com',
    bookingUrl: 'https://hampshireconsulting.com/book',
    coordinates: {
      latitude: 51.0504,
      longitude: -1.4084,
    },
  },
  {
    id: '15',
    title: 'Hampshire Training Academy',
    description:
      'Professional training and skill development courses across Hampshire.',
    price: 3500,
    rating: 4.8,
    category: {
      id: 'c10',
      name: 'Education',
      slug: 'education',
    },
    image: '/images/training.jpg',
    location: 'All Hampshire',
    address: 'Training Center, Hampshire',
    openingHours: 'Mon-Sat: 9am - 6pm',
    createdAt: new Date().toISOString(),
    phone: '+92 300 1515151',
    email: 'training@example.com',
    website: 'https://hampshiretraining.com',
    bookingUrl: 'https://hampshiretraining.com/book',
    coordinates: {
      latitude: 51.0504,
      longitude: -1.4084,
    },
  },
];
